### PR TITLE
check if picture is landscape oriented

### PR DESCRIPTION
**Pull request by xsuchy**

### CODE REVIEW

**Comment by xsuchy** [comment]
I believe that none of the Travis failures are related to this PR.

**Comment by pypingou** [comment]
Nice and easy, I'll look at the failure and get this in

**Comment by pypingou** [comment]
@xsuchy could you rebase on the top of master, I believe the tests should pass now :)

**Comment by xsuchy** [comment]
rebased

**Comment by pypingou** [comment]
Great, thanks! :)

**Pull request merged**
