### PR TITLE
Election list sorted according to publishing date

### LINKED ISSUE #76: Release schedule is messed up in the elections tab
Just noted that the elections tab has 4 Fedora release submission schedules inside. Unfortunately they are not in a chronological order. Any chance to fix that?

### PR DESCRIPTION
**Pull request by vivekanand1101**
Probably fixes #76

### CODE REVIEW

**Comment by pypingou** [comment]
I think we can do this better by doing the ordering at the SQL layer directly (cf the discussion at #76, we just need a second ordering factor in that query)

**Comment by vivekanand1101** [comment]
so, it should be `Elections.election_date_end.asc()` instead of `Elections.election_year.desc()` [here](https://github.com/fedora-infra/nuancier/blob/master/nuancier/lib/model.py#L188). The route `/elections` calls `get_elections` [here](https://github.com/fedora-infra/nuancier/blob/master/nuancier/ui.py#L187) which in turn calls class method `all` [here](https://github.com/fedora-infra/nuancier/blob/master/nuancier/lib/__init__.py#L110)

**Comment by pypingou** [comment]
I think it should be both

**Comment by vivekanand1101** [comment]
Sorry for the mess. Presently i am not able to clone the repo, so it would be better if you could verify it.

**Comment by pypingou** [comment]
I think we'll want to keep the ``desc()`` to keep the most recent elections at the top.

Otherwise it looks good (would be even nicer if you could squash the commits if you can)

**Comment by vivekanand1101** [comment]
I need help in git. I started to squash taking steps from [here](http://stackoverflow.com/questions/5189560/squash-my-last-x-commits-together-using-git/5201642#5201642). Only soft reset(last 4) and commit. But, on pushing it says me to pull first. I think if i pull again, the squashing would be useless. One way was using `-f` during pushing but i read that it can lead to [disasters](http://randyfay.com/content/avoiding-git-disasters-gory-story).

**Comment by pypingou** [comment]
``git push -f`` is required when rewriting history (which we do in this case), but to be sure, make sure to keep a pristine clone of the repo as it is now (without the rebase) so that you can always rollback :)

**Comment by vivekanand1101** [comment]
I realize that i should have committed locally to avoid this sort of problem. I might be wrong here but, from the current situation, since my last commit was merging from the upstream branch, so if i squash any commit, the commit(s) of the other people might be thrown away. Also, 5 commits for such a small change is definitely not good. So, i am closing this for now and will come clean in my next PR.

**Comment by pypingou** [comment]
It should work with rebase then squashing but depends how much you want to play with git ;-)

**Comment by vivekanand1101** [comment]
Actually i thought it was a dead end but the damage has been done now. Really sorry for the mess.

**Comment by pypingou** [comment]
No worries about that ;-)

**Pull request closed without merging**
