### PR TITLE
Switch back from unittest2 to unittest

### PR DESCRIPTION
**Pull request by jeremycline**
I very briefly fiddled with running the tests on 2.6, but decided it
wasn't worth the effort. However, I neglected to add the modified
.travis.yml file when I updated #108 so this fixes that.

Signed-off-by: Jeremy Cline <jeremy@jcline.org>

### CODE REVIEW

**Comment by pypingou** [comment]
wfm 👍

**Comment by pypingou** [comment]
Do we want to update the classifiers in the setup.py while at it then?

**Comment by jeremycline** [comment]
I added classifiers to the setup.py and fixed that typo you noticed from the original PR, as well.

**Comment by pypingou** [comment]
Cool, 👍 for me

**Pull request merged**
